### ISSUE TITLE
latest docker is 710MB - previous was 230MB - what gives ??

### ISSUE THREAD

**Issue by Zixim** [perara/wg-manager#87]
as per title

**Comment by Zixim** [comment]
so these fields are required in the new db : 
server.subnet (INTEGER)
server.v6_address (VARCHAR)
peer_1.v6_address (VARCHAR)

**Comment by perara** [comment]
Hi,
The size increase is because I changed from alpine base to ubuntu in hope of getting better support for arm devices. Generally, it should not have reached the main branch, it's just me having way too much to do these days forgetting stuff.

Related to this: Would you prefer if there are several dockerfiles, where alpine is an option? Then we would get back to ~200 MB

Your second comment: I've seen a lot of reports on this, and I'll investigate the issue.

Next up: I will do some work today (and tomorrow hopefully) on making a decent workflow for the project.
I'll look into making some unit test workflow as well, and hope for some contribution eventually so that it's easier to ensure consistency between versions.

**Comment by Zixim** [comment]
Alpine --> Ubuntu explains the jump in size... I was worried you'd left some development crud in there, causing bloat.

> Would you prefer if there are several dockerfiles, where alpine is an option? Then we would get back to ~200 MB
no preference, whichever is easiest to maintain for you!

**Comment by perara** [comment]
At the time I worked there was some bug with generating armv6-7-8 images from the alpine version, but I'll investigate if this has been fixed :)
